# تحليل وتحذيرات Dart & Flutter
# =================================

include: package:flutter_lints/flutter.yaml

# Formatter options (Dart 3.8+)
formatter:
  trailing_commas: preserve   # يحافظ على الـ commas

linter:
  rules:
    # --- Const rules ---
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    # --- Style rules ---
    avoid_print: true                # يحذر لو استخدمت print
    
    sort_child_properties_last: true # يخلي child آخر property
    always_use_package_imports: true # يستحسن تستعمل package imports

    # --- Code quality ---
    unnecessary_this: true
    avoid_unused_constructor_parameters: true
    unnecessary_const: true
    require_trailing_commas: true    # يجبرك تسيب commas آخر البراميتر
