// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEuAiNhTv4Q5X80LumywyUzerQyGte8G8',
    appId: '1:71838114684:web:5ad1c91b598d1f6b407af9',
    messagingSenderId: '71838114684',
    projectId: 'map-3b3da',
    authDomain: 'map-3b3da.firebaseapp.com',
    storageBucket: 'map-3b3da.firebasestorage.app',
    measurementId: 'G-J857HR4KGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCwOhkfoh1-zdXGBas0L0l9r9cXtC8fo',
    appId: '1:71838114684:android:46825b35fa5ec86f407af9',
    messagingSenderId: '71838114684',
    projectId: 'map-3b3da',
    storageBucket: 'map-3b3da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKu0XrGzarsTw7l4ctOXyoo2wQ0s3Z-s',
    appId: '1:71838114684:ios:378b317868a10111407af9',
    messagingSenderId: '71838114684',
    projectId: 'map-3b3da',
    storageBucket: 'map-3b3da.firebasestorage.app',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoKu0XrGzarsTw7l4ctOXyoo2wQ0s3Z-s',
    appId: '1:71838114684:ios:378b317868a10111407af9',
    messagingSenderId: '71838114684',
    projectId: 'map-3b3da',
    storageBucket: 'map-3b3da.firebasestorage.app',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEuAiNhTv4Q5X80LumywyUzerQyGte8G8',
    appId: '1:71838114684:web:825148df1ccf4cf8407af9',
    messagingSenderId: '71838114684',
    projectId: 'map-3b3da',
    authDomain: 'map-3b3da.firebaseapp.com',
    storageBucket: 'map-3b3da.firebasestorage.app',
    measurementId: 'G-9S9GHK4V4V',
  );
}
